(function(g){var window=this;'use strict';var x4=function(a){a.ma("cardstatechange",a.xk()&&a.Eo()?1:0)},y4=function(a,b){var c=g.Qa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Jcb=function(a){var b=g.kn(a);
a=g.nn(a);return new g.Zm(b.x,b.y,a.width,a.height)},B4=function(a){a=g.Va(a);
delete z4[a];g.$c(z4)&&A4&&A4.stop()},Lcb=function(){A4||(A4=new g.Tp(function(){Kcb()},20));
var a=A4;a.isActive()||a.start()},Kcb=function(){var a=g.Ya();
g.Pc(z4,function(b){Mcb(b,a)});
g.$c(z4)||Lcb()},C4=function(a,b,c,d){g.mq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.N=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.J=0;this.C=null},Mcb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;Ncb(a,a.progress);1==a.progress?(a.j=0,B4(a),a.onFinish(),a.Lq()):a.kd()&&a.nJ()},Ncb=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.N[c]-a.u[c])*b+a.u[c]},Ocb=function(a,b){g.tb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},D4=function(a,b,c,d,e){C4.call(this,b,c,d,e);
this.element=a},Pcb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
D4.call(this,a,b,c,d,e)},Qcb=function(a){return Math.pow(a,3)},Rcb=function(a){return 3*a*a-2*a*a*a},Scb=function(a){g.D.call(this);
this.u=a||window;this.j=[]},E4=function(a){return a.baseUrl||null},F4=function(a,b){return g.eo(g.sm(a,b),function(c){return!!c})},Tcb=function(a,b,c){function d(X){var ma=X.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var aa=f(ma.unsubscribedButtonText),Ca=f(ma.subscribedButtonText);if(ma.subscribed){var U=f(ma.subscriberCountWithUnsubscribeText);var Ua=f(ma.subscriberCountText)}else U=f(ma.subscriberCountText),Ua=f(ma.subscriberCountWithSubscribeText);var r=null;if(X.signinEndpoint){r=y4(X,"signinEndpoint","webNavigationEndpointData","url");if(!r){var P,vb;r=null==(vb=g.Q(null==(P=ma.signInEndpoint)?void 0:P.commandMetadata,g.q3))?void 0:vb.url}if(!r)return null}return aa&&
(Ca||r)?{subscribed:ma.subscribed,subscribeText:aa,subscribeCount:U,unsubscribeText:Ca,unsubscribeCount:Ua,enabled:ma.enabled,signinUrl:r,classic:X.useClassicSubscribeButton}:null}
function e(X){if(X){var ma=[],aa=X.videoId;aa&&ma.push("v="+aa);(aa=X.playlistId)&&ma.push("list="+aa);(X=X.startTimeSeconds)&&ma.push("t="+X);return"/watch?"+ma.join("&")}}
function f(X){if(!X)return null;var ma=X.simpleText;return ma?ma:X.runs?g.sm(X.runs,function(aa){return aa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,y=null,B=!1,G=null,N=null,L=null,H=null,V=null,Z=null;if("VIDEO"===h)g.Q(l,g.dO)?m=g.Q(l,g.dO).url:(Z=g.Q(l,g.cO),m=e(Z)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)g.Q(l,g.dO)?m=g.Q(l,g.dO).url:(Z=g.Q(l,g.cO),m=e(Z)),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"===
h){if(B=y4(l,"browseEndpoint","browseId"))y=B,m="/channel/"+y;n=!1;q="new";(B=!!b.isSubscribe)?G=d(b):N=f(b.subscribersText)}else"WEBSITE"===h?((L=y4(l,"urlEndpoint","url"))&&(m=L),n=!0,q="new",L=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(V=f(b.additionalFeesText)),(n=y4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=y4(b,"title","accessibility","accessibilityData","label");var ca=b.endpoint?b.endpoint.clickTrackingParams:null,
sa="";if(b.metadata){var la=f(b.metadata);la&&(sa=la)}return{id:"element-"+c,type:h,title:f(b.title),metadata:sa,callToAction:f(b.callToAction),yT:b.image,iconUrl:L,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,tC:p,playlistLength:v,channelId:y,subscribeButton:G,subscribersText:N,isSubscribe:B,Tt:m||null,x4:n,sessionData:ca?{itct:ca}:null,p9:q,UA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:F4(b.impressionUrls||[],E4),m4:F4(b.hovercardShowUrls||[],E4),clickUrls:F4(l.loggingUrls||[],E4),visualElement:g.$F(b.trackingParams),productPrice:H,additionalFeesText:V,watchEndpoint:Z||null}},Ucb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:F4(a.impressionUrls||[],E4),elements:F4(a.elements||[],function(d,e){return Tcb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.$F(a.trackingParams));return c},Vcb=function(a){g.aU.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.N=[];this.ea=!0;this.J=0;a=a.W();this.V=g.YL(a)||"profilepage"===a.Na;this.events=new g.MJ(this);g.I(this,this.events);this.events.T(this.player,g.zF("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.AF("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Hb);this.events.T(window,"focus",this.X7);this.load();var b=g.Xe("STYLE");(g.Me("HEAD")[0]||document.body).appendChild(b);g.ob(this,
function(){g.ff(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Wcb=function(a){return a.player.getVideoData().zd?"current":a.V?"new":"current"},G4=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},Xcb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Ucb(f,Wcb(a))));H4(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.Vw;d&&(c.postParams={ad_tracking:d});if(b=g.pya(b))if(b=g.$d(b),b=g.Yd(b))a.B=g.az(b,c)},H4=function(a,b,c){c=void 0===c?!0:c;
a.player.Me("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&Ycb(a);c=[];d=new g.xF(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().u||(a.u=new g.W({G:"div",S:"ytp-ce-shadow"}),g.$S(a.player,a.u.element,4),a.C=new g.CR(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Zcb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.$S(a.player,f.element,4);var h=new g.xF(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);$cb(a,f,e)}else g.dF(new g.xA("buildEndscreenElement null",
e))}a.player.bf(c);a.Hb()}},Ycb=function(a){var b=g.bG(),c=g.cG();
c&&b&&a.endscreen.visualElement&&g.Hy(g.oQ)(void 0,c,b,a.endscreen.visualElement)},Zcb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",La:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.UA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:I4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:J4(a,b.Tt),tabindex:"-1"},X:[{G:"div",La:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.qq(b.title||"")},xa:b.title},{G:"div",S:b.tC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",xa:b.videoDuration||
void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={G:"div",La:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.UA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:I4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:J4(a,b.Tt),tabindex:"-1"},X:[{G:"div",La:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.qq(b.title||"")},xa:b.title},{G:"div",S:"ytp-ce-playlist-count",X:[{G:"div",S:"ytp-ce-playlist-icon"},
{G:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={G:"div",La:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.UA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"a",La:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:J4(a,b.Tt),target:"_blank",tabindex:"-1",dir:g.qq(b.title||"")},xa:b.title},b.subscribeButton?{G:"div",S:"ytp-ce-subscribe-container",X:[{G:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{G:"div",La:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
xa:b.metadata}:""]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:I4(b)}]};c=new g.W(c);var d=g.Ne(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.aq(d,"ytp-ce-subscribe-button");if(a.player.W().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.JU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={G:"div",La:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.UA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-website-title",Y:{dir:g.qq(b.title||"")},xa:b.title},{G:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{G:"a",La:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:J4(a,b.Tt),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:I4(b)},{G:"div",S:"ytp-ce-expanding-icon",Y:adb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",S:"ytp-ce-merchandise-price-container",
X:[{G:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.X.push({G:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={G:"div",La:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.UA||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",
X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.qq(b.title||"")},xa:b.title},c,{G:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{G:"a",La:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:J4(a,b.Tt),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:I4(b)},{G:"div",S:"ytp-ce-merchandise-invideo-cta-container",X:[{G:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.aq(c.element,"ytp-ce-placeholder");return c},I4=function(a){if(a.yT)var b=a.yT.thumbnails;
return adb(b?b[b.length-1].url:null)},adb=function(a){return a?{style:"background-image: url("+a+")"}:{}},$cb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.aq(b.element,"ytp-ce-force-expand"),K4(a,c.id,!0)):(g.cq(b.element,"ytp-ce-force-expand"),g.cq(b.element,"ytp-ce-element-hover"),K4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){bdb(a,b,c)});
b.Ta("mouseleave",function(){cdb(a,b,c)});
a.player.W().u||b.Ta("click",function(){g.aq(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){ddb(a,c,m)});
b.Ta("keypress",function(m){ddb(a,c,m)});
b.Ta("focus",function(){bdb(a,b,c)});
b.Ta("blur",function(){cdb(a,b,c)});
b.Ta("touchstart",function(){bdb(a,b,c)});
var l=g.Re("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){g.XP?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.cq(b.element,"ytp-ce-element-hover");g.cq(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.Re("ytp-sb-subscribe",b.element));d(g.Re("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},ddb=function(a,b,c){if(b.Tt&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.$p(d,"ytp-ce-element");){g.$p(d,"subscribe-label")&&edb(a,b);
if(g.$p(d,"ytp-ce-channel-subscribe"))return;d=g.gf(d)}if(!d||g.$p(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])cdb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.p9)edb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.$d(J4(a,b.Tt)),g.sP(g.Yd(c),void 0,b.sessionData);else{var e=g.pM(a.player.W())||a.player.getVideoData().zd,f=function(){var h=J4(a,b.Tt),l=b.sessionData,m=b.watchEndpoint,n=g.Ny(h);e&&n&&(n.v||n.list)?a.player.Tn(n.v,
l,n.list,!1,void 0,m||void 0):g.qP(h,l)};
edb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},J4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.yM(a)+b}else return"";return b},bdb=function(a,b,c){g.$p(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.aq(b.element,"ytp-ce-element-hover"):a.player.W().u?(new g.Tp(function(){g.aq(b.element,"ytp-ce-element-hover")},200)).start():g.aq(b.element,"ytp-ce-element-hover"),L4(a,c.m4),K4(a,c.id,!0))},cdb=function(a,b,c){g.cq(b.element,"ytp-ce-element-hover");
g.cq(b.element,"ytp-ce-force-expand");K4(a,c.id,!1)},K4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.eq(a.j[e].element,"ytp-ce-element-shadow-show",c)},L4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||G4(a))c&&c();else{b=fdb(a,b);var e=0,f=!1,h=new g.Tp(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.pC(b[a],d)}},edb=function(a,b,c){L4(a,b.clickUrls,c);
(a=g.cG())&&b.x4&&g.uQ(a,b.visualElement)},fdb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(gdb(b[d],c));return a},gdb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},hdb=function(a){return"string"===typeof a?a:""},M4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},idb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},N4=function(a){return a.value?a.value:null},O4=function(a){if(!a)return null;
var b=g.$d(hdb(a.value));b=g.Yd(b);if(!b)return null;var c=M4(a.target,jdb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new idb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},kdb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},ndb=function(a){if(!a)return null;
var b=M4(a.type,ldb),c=M4(a.trigger,mdb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=O4(a?a:null);return b?new kdb(b,c,a):null},odb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},pdb=function(a,b){return g.zb(a.action,b)},qdb=function(a,b){this.context=a;
this.j=b},rdb=function(a){return a.customMessage?P4("div","iv-card-message",a.customMessage):""},Q4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",S:"iv-card-image",Y:{style:a},X:c}},sdb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(P4("li","",c.value));return{G:"ul",S:"iv-card-meta-info",X:b}},P4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.qq(c);return{G:a,Y:b,xa:c}},tdb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.dB&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.dB+");");c.dir=g.qq(a.customMessage);var d=[{G:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",S:"iv-card-link-icon"}));return{G:"div",La:b,Y:c,X:d}},R4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Vi.click,5)}},udb=function(a,b){this.merchant=a;
this.price=b},vdb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},wdb=function(a,b){return b?b:vdb(a)?"current":"new"},S4=function(a,b){g.D.call(this);
var c=this;this.element=a;this.context=b;this.ub=!1;this.eb=new Map;this.ib=new Map;this.context.I.addEventListener(g.zF("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.AF("annotations_module"),function(d){(d=c.ib.get(d))&&d.apply(c)})},T4=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.oJ(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.ub=!1});
a.context.j.Ta(b,"touchmove",function(){a.ub=!0})},xdb=function(a){var b;
return(null==(b=g.Q(a,g.dO))?0:b.url)?g.Q(a,g.dO).url:(a=g.Q(a,g.cO))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},U4=function(a,b,c){return{RU:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
oY:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
xI:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},ydb=function(a,b,c){S4.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Na=this.Rb=this.B=this.isInitialized=!1;this.cards=[];this.Ob=this.V=this.Ja=this.D=this.Va=this.j=null;this.oa=[];this.qa=this.N=this.pg=this.Ca=null;this.J=0;this.Fa=new g.Tp(function(){},c.Z.Hi?4E3:3E3);
g.I(this,this.Fa);this.qb=new g.Tp(function(){});
g.I(this,this.qb);this.Aa=new qdb(c,function(e,f,h,l,m,n){T4(d,e,f,h,l,m,n)});
this.ea=new g.W({G:"div",S:"iv-drawer",Y:{id:"iv-drawer"},X:[{G:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{G:"span",S:"iv-drawer-header-text"},{G:"button",La:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{G:"div",S:"iv-drawer-content"}]});g.I(this,this.ea);this.C=this.ea.element;this.kb=new g.CR(this.ea,330);g.I(this,this.kb);this.Qb=g.Re("iv-drawer-header-text",this.C);this.u=g.Re("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&V4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.B)&&W4(d)});
this.Oa=new g.MJ(this);g.I(this,this.Oa);this.I.addEventListener("videodatachange",this.Ns.bind(this))},zdb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){V4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){W4(a)});
var c=b.headerText;g.jf(a.Qb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ca=g.$F(b.trackingParams);a.N=g.$F(b.closeTrackingParams);a.pg=g.$F(b.iconTrackingParams)},Adb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J,d=a.I.W().experiments.rb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.FF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Vi:{},Fo:null,ql:e.trackingParams?g.$F(e.trackingParams):null,pg:f&&f.trackingParams?g.$F(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
dB:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};X4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.FF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:Y4(a,c,b,f),sponsored:!1,Vi:U4(f,e,f.command),Fo:f.trackingParams?g.$F(f.trackingParams):null,ql:e.trackingParams?g.$F(e.trackingParams):null,pg:l&&l.trackingParams?g.$F(l.trackingParams):null,imageUrl:Z4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.FF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,dB:null,title:f.title?g.FF(f.title):"",customMessage:f.callToAction?g.FF(f.callToAction):"",url:g.Q(f.command,g.dO).url?O4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.dO).url}):null,onClickCommand:null};X4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.FF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Vi:U4(e,f,e.endpoint),Fo:e.trackingParams?g.$F(e.trackingParams):null,ql:f.trackingParams?g.$F(f.trackingParams):null,pg:l&&l.trackingParams?g.$F(l.trackingParams):null,channelId:g.Q(e.endpoint,g.p3).browseId,customMessage:e.customText?g.FF(e.customText):null,eX:Z4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.FF(e.channelName):"",metaInfo:[e.subscriberCountText?g.FF(e.subscriberCountText):""],url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.p3).canonicalBaseUrl?g.Q(e.endpoint,g.p3).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.p3).browseId}),onClickCommand:null};X4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.FF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Vi:U4(e,f,e.action),Fo:e.trackingParams?g.$F(e.trackingParams):null,ql:f.trackingParams?g.$F(f.trackingParams):null,pg:l&&l.trackingParams?g.$F(l.trackingParams):null,jE:Z4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.FF(e.customMessage):null,playlistVideoCount:g.FF(e.playlistVideoCount),title:e.playlistTitle?g.FF(e.playlistTitle):"",metaInfo:[e.channelName?g.FF(e.channelName):
"",e.videoCountText?g.FF(e.videoCountText):""],url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:xdb(e.action)}),onClickCommand:null};X4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.FF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Vi:U4(e,f,e.action),Fo:e.trackingParams?g.$F(e.trackingParams):null,ql:f.trackingParams?g.$F(f.trackingParams):null,pg:l&&l.trackingParams?g.$F(l.trackingParams):null,jE:Z4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.FF(e.lengthString):null,customMessage:e.customMessage?g.FF(e.customMessage):null,title:e.videoTitle?g.FF(e.videoTitle):"",metaInfo:[e.channelName?g.FF(e.channelName):
"",e.viewCountText?g.FF(e.viewCountText):""],isLiveNow:!!e.badge,url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:xdb(e.action)}),onClickCommand:null};X4(a,b)}}}}}a.J++},Z4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},Y4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Cdb=function(a,b){if(b=Bdb(a,b))b===a.j&&(a.j=null),a.I.removeCueRange(b.jg.id),g.ff(b.TK),g.Db(a.cards,b),a.eF(),$4(a)},V4=function(a,b,c){if(!a.B){a.kb.show();
a.Va=new g.Tp(function(){g.aq(a.context.I.getRootNode(),g.xX.IV_DRAWER_OPEN)},0);
a.Va.start();a.Oa.T(a.u,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.cG();d&&a.Ca&&a.N&&g.sQ(d,[a.Ca,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.CV||(f.CV=!0,Ddb(a.context.logger,f.jg.Vi.RU,b)),d&&g.sQ(d,[f.jg.Fo]);x4(a.I);c&&(a.D=new g.Tp(function(){a.Ja=a.V;a.Ob.focus()},330),a.D.start())}},W4=function(a){a.B&&(a.kb.hide(),g.gA(a.Oa),g.cq(a.context.I.getRootNode(),g.xX.IV_DRAWER_OPEN),a.B=!1,x4(a.I),a.D&&a.D.stop(),a.D=new g.Tp(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},Fdb=function(a){g.bq(a.xb(),
[g.xX.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.$S(a.I,a.C,5);Edb(a);a.V=g.Re("ytp-cards-button",a.I.getRootNode());a.Ob=g.Re("iv-drawer-close-button",a.C);a.isInitialized=!0},Edb=function(a){var b=g.Re("iv-drawer-close-button",a.C);
a.context.j.Ta(b,"click",a.A2,a);a.context.j.Ta(a.u,"touchend",function(){a.Fa.start()});
a.context.j.Ta(a.u,"scroll",a.R2,a);a.context.u.subscribe("onHideControls",function(){a.Na=!0});
a.context.u.subscribe("onShowControls",function(){a.Na=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Na=g.$p(a.I.getRootNode(),"ytp-autohide")});
a.oa.push(g.GC("iv-button-shown",a.I4,a));a.oa.push(g.GC("iv-button-hidden",a.H4,a));a.oa.push(g.GC("iv-teaser-shown",a.YZ,a));a.oa.push(g.GC("iv-teaser-hidden",a.J4,a));a.oa.push(g.GC("iv-teaser-clicked",a.XZ,a))},Gdb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.Q(b.onClickCommand,g.t$a))?void 0:c.targetId)?(a.qa=b,!0):!1},Hdb=function(a,b){a.qa=b;
var c=a.I.getVideoData();if(!c)return!1;c=a.I.K("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.wN(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.Q(h[0],g.nOa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},
X4=function(a,b){if(!Gdb(a,b)||Hdb(a,b)){var c=Idb(a,b);
if(c){var d={jg:b,TK:c.element,CV:!1};if(!b.onClickCommand){a.isInitialized||Fdb(a);Cdb(a,b.id);var e=Jdb(a,d);g.Kb(a.cards,e,0,d);c.Ha(a.u,e);a.eF()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,$4(a),Kdb(a,d),V4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&Ldb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Ldb(a,d)}),$4(a))}}},Idb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{G:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=tdb(b);c={G:"div",La:["iv-card"],X:[{G:"a",S:"iv-click-target",Y:{href:b.url?N4(b.url)||"":""},X:[Q4(b.imageUrl,c),{G:"div",S:"iv-card-content",X:[P4("h2",void 0,b.title),d]}]}]};c=new g.W(c);R4(a,g.Qe("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={G:"div",La:["iv-card","iv-card-channel"],X:[{G:"a",La:["iv-click-target"],Y:{href:N4(b.url)||"","data-ytid":b.channelId},X:[Q4(b.eX),{G:"div",
S:"iv-card-content",X:[rdb(b),{G:"h2",S:"iv-card-primary-link",xa:b.title},sdb(b)]}]}]};c=new g.W(c);R4(a,g.Qe("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={G:"div",La:["iv-card","iv-card-playlist"],X:[{G:"a",S:"iv-click-target",Y:{href:N4(b.url)||""},X:[Q4(b.jE,{G:"div",S:"iv-card-image-overlay",X:[{G:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{G:"div",S:"iv-card-content",X:[rdb(b),P4("h2","iv-card-primary-link",b.title),sdb(b)]}]}]};c=new g.W(c);
R4(a,g.Qe("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=tdb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({G:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={G:"div",X:e});e=b.url?N4(b.url)||"":"";c={G:"div",La:c,Y:{tabindex:"0"},X:[{G:"a",La:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",S:"iv-card-content",X:[b.sponsored?{G:"div",S:"iv-card-sponsored",X:["Patrocinado",{G:"div",S:"iv-ad-info-container",X:[{G:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{G:"div",S:"iv-ad-info-icon-container",X:[{G:"div",S:"iv-ad-info-icon"},{G:"div",S:"iv-ad-info-callout"}]}]}]}:"",{G:"a",S:"iv-click-target",Y:{href:e},X:[P4("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Xe("span");g.jf(d,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");
c.ke(d,"adInfo");R4(a,g.Qe("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{G:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{G:"span",La:["yt-badge","yt-badge-live"],xa:"EN DIRECTO AHORA"}:null;e={G:"div",La:["iv-card","iv-card-video"],X:[{G:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:N4(c))||""},X:[Q4(b.jE,d),{G:"div",S:"iv-card-content",X:[rdb(b),P4("h2","iv-card-primary-link",b.title),sdb(b),f]}]}]};c=new g.W(e);R4(a,
g.Qe("iv-click-target",c.element),b,b.url);b=c;break;default:return null}return b},Jdb=function(a,b){if(0===a.cards.length)return 0;
a=g.Ab(a.cards,function(c){return b.jg.startMs>c.jg.startMs||b.jg.startMs===c.jg.startMs&&b.jg.timestamp>=c.jg.timestamp?!0:!1});
return-1===a?0:a+1},Mdb=function(a){if(a.j)return"productListing"===a.j.jg.type;
if(a.I.K("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.tm(a.cards,function(c){return"productListing"===c.jg.type})}return g.tm(a.cards,function(c){return"productListing"===c.jg.type})},$4=function(a){g.eq(a.I.getRootNode(),"ytp-cards-shopping-active",Mdb(a))},Ldb=function(a,b){if(!g.$p(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.cG(),d=a.j?a.j.jg.pg:a.pg;
c&&d&&g.tQ(c,[d]);a.j=b;$4(a)}(c=a.isInitialized&&"none"==a.xb().style.display)||(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=!(1===c||3===c||d));c||b.jg.teaserDurationMs&&a.I.Oz(!0,{teaserText:b.jg.teaserText,durationMs:b.jg.teaserDurationMs,onClickCommand:b.jg.onClickCommand});a.qb.isActive()||((!a.B||!a.Fa.isActive()&&a.Na)&&Kdb(a,b),a.qb.start(910+b.jg.teaserDurationMs))}},Kdb=function(a,b){a.ea.Cb?(b=new C4([0,
a.u.scrollTop],[0,b.TK.offsetTop],600,Rcb),a.context.B.Ta(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ta(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.dR(a.ea,!0),a.u.scrollTop=b.TK.offsetTop,g.dR(a.ea,!1))},a5=function(a){return a.j&&a.j.jg?a.j.jg:a.cards[0]&&a.cards[0].jg?a.cards[0].jg:null},Bdb=function(a,b){return g.zb(a.cards,function(c){return c.jg.id===b})},b5=function(a,b,c){S4.call(this,a,b);
this.annotation=c;this.isActive=!1},Ndb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},c5=function(a,b,c){b5.call(this,a,b,c);
this.u=null;this.N=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},Odb=function(a,b){var c=void 0===c?0:c;
var d=Jcb(b).width;g.hn(b,d);c=new Pcb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Qcb);g.I(a,c);a.context.B.Ta(c,"begin",function(){g.on(b,!0)});
c.play()},Rdb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
La:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({G:"div",La:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.JU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.I),a.j.Ha(d));var f=a.createElement({G:"div",La:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",La:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.on(h,!1);var l=a.createElement({G:"div",La:["branding-context-container-outer"]});l.appendChild(h);g.bn(l,"right",b.image_width+"px");g.Ze(a.xb(),l);a.B=new g.Tp(function(){Pdb(a,h,l)},500);
g.I(a,a.B);a.context.j.Ta(a.xb(),"mouseover",function(){Qdb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.xb(),"mouseout",function(){a.B.start()})}},Qdb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.nn(b);a.j||(b.style.width=g.gn(f.width,!0),c.style.width=g.gn(f.width,!0));g.bn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.bn(d,"right","1px");a.C=!0;g.on(b,!0);a.D=new g.Tp(function(){g.aq(this.xb(),"iv-branding-active")},0,a);
a.D.start()}},Pdb=function(a,b,c){g.cq(a.xb(),"iv-branding-active");
a.J=new g.Tp(function(){g.on(b,!1);a.j||(c.style.width=g.gn(0,!0))},250);
a.J.start();a.C=!1},Sdb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},Tdb=function(a,b,c){b5.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.ea=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.N=this.createElement({G:"div",La:["iv-promo-contents"]});this.D=new g.Tp(function(){d.j.setAttribute("aria-hidden","true");g.on(d.B,!1);g.on(d.u,!0)},700,this);
g.I(this,this.D)},Vdb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.xb().setAttribute("aria-hidden","true");a.xb().setAttribute("aria-label","Promoci\u00f3n");a.xb().tabIndex=0;var e=a.annotation.mf(),f=b.image_url;if(f){var h=a.createElement({G:"div",La:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&T4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",S:"iv-promo-txt"}),g.le(f,N4(e)),a.j=f):a.j=a.createElement({G:"div",S:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",X:[{G:"strong",xa:b.text_line_1}]});
var m=a.createElement({G:"p",X:[{G:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",La:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",La:["iv-button","iv-promo-button"],X:[{G:"span",S:"iv-button-content",xa:f}]});var p=a.createElement({G:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&T4(a,a.xb(),e,a.annotation.id,b.session_data,void 0,c)}g.aq(a.j,"iv-click-target");
e&&T4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",X:[{G:"span",xa:b.text_line_1}]}),m=a.createElement({G:"p",X:[{G:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",La:["yt-badge","iv-promo-badge-live"],xa:"EN DIRECTO AHORA"})),g.aq(a.j,"iv-click-target"),e&&T4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.N.appendChild(a.j);p&&a.N.appendChild(p);
c=a.createElement({G:"div",S:"iv-promo-actions"});a.u=a.createElement({G:"button",La:["iv-promo-expand","ytp-button"]});a.u.title="Expandir";a.context.j.Ta(a.u,"click",function(q){Udb(a,5E3,q)});
c.appendChild(a.u);g.on(a.u,!1);a.context.j.Ta(a.xb(),"mouseover",a.O3,a);a.context.j.Ta(a.xb(),"mouseout",a.N3,a);a.context.j.Ta(a.xb(),"touchend",function(q){Udb(a,5E3,q)});
a.B=a.createElement({G:"button",La:["iv-promo-close","ytp-button"]});a.B.title="Cerrar";a.context.j.Ta(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.J3:a.I3,a);c.appendChild(a.B);g.bq(a.xb(),d);h&&(g.Ze(a.xb(),h),n&&h.appendChild(n));g.Ze(a.xb(),a.N);g.Ze(a.xb(),c)},Udb=function(a,b,c){c.stopPropagation();
Wdb(a);Xdb(a,b);a.j.focus()},Ydb=function(a){a.isCollapsed||a.V||a.C||(g.aq(a.xb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Wdb=function(a){a.D.stop();
a.isCollapsed&&(g.dq(a.xb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.on(a.u,!1),g.on(a.B,!0))},Xdb=function(a,b){a.C||(a.C=g.Mf(function(){Zdb(this);
Ydb(this)},b,a))},Zdb=function(a){a.C&&(g.La.clearTimeout(a.C),a.C=null)},$db=function(a){this.I=a},Ddb=function(a,b,c){b&&(c?d5(a,b.map(function(d){return g.Ip(d,c)})):d5(a,b))},d5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.pC(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},aeb=function(a){g.aU.call(this,a);
var b=this;this.ea=this.N=!1;this.loadNumber=0;this.J={};this.logger=new $db(this.player);this.C=new g.MJ(this);this.D=this.Fw=null;this.events=new g.MJ(this);this.lh=this.V=this.j=null;this.oa=[];g.I(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ma("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.ZZ,this);this.subscribe("resize",this.nH,this);this.player.W().Ja.subscribe("vast_info_card_add",this.NW,this);g.I(this,this.events);this.qa=this.createElement({G:"div",S:"video-custom-annotations"});this.u=new g.W({G:"div",La:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.$S(this.player,this.u.element,4);this.u.hide();this.B=new g.W({G:"div",La:["ytp-iv-video-content"]});g.I(this,this.B);a=this.createElement({G:"div",S:"video-annotations"});
a.appendChild(this.qa);this.B.element.appendChild(a);this.ww()&&this.load();var c=this.createElement({G:"style"});(g.Me("HEAD")[0]||document.body).appendChild(c);g.ob(this,function(){g.ff(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},beb=function(a){a=a.createElement({G:"div",
La:["annotation","annotation-type-custom"]});g.on(a,!1);return a},ceb=function(a,b){b=!b.isCued()&&!g.BP(b,1024);
g.dR(a.u,b);g.dR(a.B,b)},deb=function(a,b,c){a.N=!0;
a.D=g.az(b,c)},eeb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ra(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(eeb(a,e))}return c},ieb=function(a){var b=a.player.getVideoData();
if(b.Oa){var c=a.player.W().Ja.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Vy(h)&&h.responseXML?h.responseXML:null)&&feb(a,h)}};
g.FA()&&(d.onFinish=geb(a,d.onFinish));d.postParams={ic_only:"1"};heb(d,c);a.N=!0;g.az(b.Oa,d)}}},heb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.fB&&(a.postParams.ic_coll=b.fB);b.UK&&(a.postParams.ic_xml=b.UK);b.AI&&(a.postParams.ic_track=b.AI)},jeb=function(a){var b=new g.W({G:"div"});
g.on(b.element,!1);var c=new ydb(a.player,b.element,e5(a));g.I(c,b);b.Ha(a.u.element);c.YD();return c},e5=function(a){if(!a.V){var b=new Scb(a);
g.I(a,b);var c=new g.pl(a);g.I(a,c);a.V=new Sdb(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.Ei)}return a.V},feb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.cG();if(e){var f=g.bG();f&&g.Hy(g.iAa)(void 0,e,f,[g.$F(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=eeb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=M4(f.type,keb),p=M4(f.style,leb),q=hdb(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=ndb;if(null==v)var y=null;else if(g.Qa(v)){l=[];for(var B=g.u(v),G=B.next();!G.done;G=B.next()){var N=f(G.value);
N&&l.push(N)}y=l}else{var L=f(v);y=L?[L]:[]}e=m&&n?new odb(m,n,p,y,t):null}else e=null}catch(la){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=beb(f),V=null;switch(l.type){case "branding":if(f.player.W().Xd)break;f.u.element.appendChild(H);V=new c5(H,e5(f),l);break;case "promotion":g.$S(f.player,H,4),V=new Tdb(H,e5(f),l)}V&&V.YD();if(f=V)g.I(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=jeb(a),g.I(a,a.j));if("card"===e.type){c=a.j;var Z=e&&e.data&&e.data.card_type;
f=e.data;if(Z)switch(l=f.tracking||{},l={RU:l.impression,click:l.click,close:l.close,oY:l.teaser_impression,xI:l.teaser_click},H=f.tracking_params||{},V=null,Z){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Vi:l,Fo:H.card?g.$F(H.card):null,ql:H.teaser?g.$F(H.teaser):null,pg:H.icon?g.$F(H.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,eX:f.image_url,title:f.title,metaInfo:f.meta_info,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Vi:l,Fo:H.card?g.$F(H.card):null,ql:H.teaser?
g.$F(H.teaser):null,pg:H.icon?g.$F(H.icon):null,jE:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "productListing":f.signin_url&&(V=O4({target:"current",value:f.signin_url}));Z=[];for(var ca=f.offers||[],sa=0;sa<ca.length;sa++)Z.push(new udb(g.Fe(ca[sa].merchant),g.Fe(ca[sa].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Vi:l,Fo:H.card?g.$F(H.card):null,ql:H.teaser?g.$F(H.teaser):null,pg:H.icon?g.$F(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,dB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Y9a:V,X9a:f.signin_title?f.signin_title:void 0,W9a:f.signin_message?f.signin_message:void 0,offers:Z,onClickCommand:null};X4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Vi:l,Fo:H.card?g.$F(H.card):
null,ql:H.teaser?g.$F(H.teaser):null,pg:H.icon?g.$F(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,dB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Vi:l,Fo:H.card?g.$F(H.card):null,ql:H.teaser?g.$F(H.teaser):null,pg:H.icon?g.$F(H.icon):null,jE:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},X4(c,e)}}else zdb(a.j,e);c=!0}}c&&
(x4(a.player),a.nH())},meb=function(a,b){var c=!1;
a.j||(a.j=jeb(a),g.I(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Adb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.zO(f)||(c=a.j,d=b.headerText?g.FF(b.headerText):"",g.jf(c.Qb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ca=b.trackingParams?g.$F(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.$F(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.pg=b.icon.infoCardIconRenderer.trackingParams?g.$F(b.icon.infoCardIconRenderer.trackingParams):null,a.nH());x4(a.player)}},neb=function(a,b,c,d,e){if(!a.player.W().Xd){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.p3)&&g.Q(b.navigationEndpoint,g.p3).browseId&&f.push(new kdb("openUrl","click",new idb("/channel/"+g.Q(b.navigationEndpoint,g.p3).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.sO)){d.channel_id=g.Q(b.subscribeButton,g.sO).channelId;var l;b=g.Q(b.subscribeButton,g.sO);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.FF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.FF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.FF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.FF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.Q(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.q3))?void 0:m.url)||"";l={subscribeText:g.FF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.FF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new odb(c,"branding","branding",f,d);l=beb(a);a.u.element.appendChild(l);f=new c5(l,e5(a),f);f.YD();g.I(f,f);a.J[c]=f}},geb=function(a,b){return function(){var c=g.Ea.apply(0,arguments);
a.isDisposed()||a.oa.push(g.Lp.Fi(function(){b.apply(null,g.oa(c))}))}},oeb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.TS.prototype.Oz=g.da(18,function(a,b){var c=g.oU(this.zb());c&&c.Oz(a,b)});
var z4={},A4=null;g.ab(C4,g.mq);g.k=C4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.kd())return!1;B4(this);this.startTime=a=g.Ya();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.eH();this.Ml("play");-1==this.j&&this.Ml("resume");this.j=1;var b=g.Va(this);b in z4||(z4[b]=this);Lcb();Mcb(this,a);return!0};
g.k.stop=function(a){B4(this);this.j=0;a&&(this.progress=1);Ncb(this,this.progress);this.Ml("stop");this.Lq()};
g.k.pause=function(){this.kd()&&(B4(this),this.j=-1,this.Ml("pause"))};
g.k.va=function(){0==this.j||this.stop(!1);this.Ml("destroy");C4.Jf.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.nJ=function(){this.Ml("animate")};
g.k.Ml=function(a){this.dispatchEvent(new Ocb(a,this))};
g.ab(Ocb,g.tb);g.ab(D4,C4);D4.prototype.B=function(){};
D4.prototype.nJ=function(){this.B();D4.Jf.nJ.call(this)};
D4.prototype.Lq=function(){this.B();D4.Jf.Lq.call(this)};
D4.prototype.eH=function(){this.B();D4.Jf.eH.call(this)};
g.ab(Pcb,D4);Pcb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(Scb,g.D);g.k=Scb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.Wa)(c,d||this.u);a=g.Zz(a,b,c);this.j.push(a);return a};
g.k.HG=function(a,b,c,d){c=(0,g.Wa)(c,d||this.u);a=g.gna(a,b,c);this.j.push(a);return a};
g.k.Jc=function(a){g.$z(a);g.Db(this.j,a)};
g.k.If=function(){g.$z(this.j);this.j.length=0};
g.k.va=function(){this.If();g.D.prototype.va.call(this)};g.x(Vcb,g.aU);g.k=Vcb.prototype;g.k.load=function(){g.aU.prototype.load.call(this);if(!G4(this)){var a=g.qya(this.player.getVideoData());a?(a=Ucb(a,Wcb(this)),H4(this,a,!1)):Xcb(this)}};
g.k.unload=function(){H4(this,null);this.B&&(this.B.abort(),this.B=null);g.aU.prototype.unload.call(this)};
g.k.Bh=function(a,b){return G4(this)?"loadCustomEndscreenRenderer"===a?(a=Ucb(b,"new"),H4(this,a),!0):null:null};
g.k.getOptions=function(){return G4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Hb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<peb.length;f++){var h=Math.abs(b.width-peb[f]);if(-1===e||d>=h)e=f,d=h}d=qeb[e];this.u&&g.bn(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.mn(e.element,m,f);g.hn(e.element,n,p);g.dq(e.element,reb);256<m||256<f?g.aq(e.element,"ytp-ce-large-round"):96<m||96<f?g.aq(e.element,"ytp-ce-medium-round"):g.aq(e.element,"ytp-ce-small-round");g.dq(e.element,seb);m=h.left+h.width/2;h=h.top+l/2;g.aq(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.dq(e.element,qeb);g.aq(e.element,d);(e=g.Ne(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.bn(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())L4(this,this.endscreen.impressionUrls),(a=g.cG())&&this.endscreen.visualElement&&g.rQ(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.aq(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.aq(b,"ytp-ce-shown");L4(this,c.impressionUrls);(b=g.cG())&&g.rQ(b,c.visualElement);this.player.W().J&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.cq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.cq(b,"ytp-ce-shown");this.player.W().J&&this.player.Qa("endscreenelementhidden",a)}};
g.k.X7=function(a){var b=this;a.target===window&&(new g.Tp(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.dq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var peb=[346,426,470,506,570,640,853,1280,1920],qeb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),seb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],reb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var jdb={nna:"current",lLa:"new"};var ldb={CLOSE:"close",KOa:"openUrl",SUBSCRIBE:"subscribe"},mdb={Rla:"click",CLOSE:"close",Axa:"hidden",zTa:"rollOut",ATa:"rollOver",WUa:"shown"};odb.prototype.mf=function(){var a=pdb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var leb={cha:"anchored",sZ:"branding",CHANNEL:"channel",dna:"cta",Dxa:"highlightText",yBa:"label",PLAYLIST:"playlist",eRa:"popup",BXa:"speech",SUBSCRIBE:"subscribe",B_a:"title",VIDEO:"video",w5a:"website"},keb={sZ:"branding",Oja:"card",jpa:"drawer",Cxa:"highlight",uHa:"marker",uSa:"promotion",TEXT:"text",V6a:"widget"};g.x(S4,g.D);g.k=S4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.xF(a,b,{id:c,namespace:"annotations_module"});d&&this.eb.set(a,d);e&&this.ib.set(a,e);this.context.I.bf([a])};
g.k.YD=function(){this.context.u.subscribe("resize",this.eF,this)};
g.k.xb=function(){return this.element};
g.k.oJ=function(a,b,c,d,e,f){if(this.ub)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ff(this.xb())};
g.k.eF=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=N4(a);if(f){var h=wdb(f,a.target),l=function(){a.j&&e.context.I.pauseVideo();var m=e.context.videoData.zd||!1,n=g.Ny(f||"");m&&n&&(n.v||n.list)?e.context.I.Tn(n.v,b,n.list,!1):g.sP(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);d5(this.context.logger,c,l,d);vdb(f)||(c=g.cG(),d=b.itct,c&&d&&g.uQ(c,g.$F(d)))}};
g.k.va=function(){this.eb.clear();this.ib.clear();g.D.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.I(this,a);return a.element};g.x(ydb,S4);g.k=ydb.prototype;g.k.Ns=function(){this.qa&&X4(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.nn(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.eF=function(){var a=this.isAvailable();g.on(this.xb(),a);g.eq(this.context.I.getRootNode(),g.xX.IV_DRAWER_ENABLED,a);x4(this.I)};
g.k.destroy=function(){this.I.Oz(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.HC(this.oa);g.gA(this.Oa);this.Va&&this.Va.dispose();this.D&&this.D.dispose();S4.prototype.destroy.call(this)};
g.k.A2=function(){if(this.B){d5(this.context.logger,a5(this).Vi.close);var a=g.cG();a&&this.N&&g.uQ(a,this.N);W4(this)}};
g.k.R2=function(){g.eq(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.I4=function(){var a=g.cG(),b=a5(this);b=b?b.pg:this.pg;a&&b&&g.sQ(a,[b])};
g.k.H4=function(){var a=g.cG(),b=a5(this);b=b?b.pg:this.pg;a&&b&&g.tQ(a,[b])};
g.k.YZ=function(){var a=a5(this);d5(this.context.logger,a.Vi.oY);var b=g.cG();b&&a&&g.sQ(b,[a.ql,a.pg])};
g.k.J4=function(){var a=g.cG(),b=a5(this);a&&b&&g.tQ(a,[b.ql])};
g.k.XZ=function(a){var b=a5(this),c=g.cG();this.j?a?(a=this.context.logger,d5(a,b.Vi.xI),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.ql&&g.uQ(c,b.ql)):(a=this.context.logger,d5(a,b.Vi.xI),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.pg&&g.uQ(c,b.pg)):(a=this.context.logger,d5(a,b.Vi.xI),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.pg&&g.uQ(c,this.pg))};g.x(b5,S4);b5.prototype.YD=function(){S4.prototype.YD.call(this);Ndb(this)};
b5.prototype.show=function(){S4.prototype.show.call(this);var a=g.cG(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.sQ(a,[g.$F(b.itct)])};
b5.prototype.hide=function(){S4.prototype.hide.call(this);var a=g.cG(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.tQ(a,[g.$F(b.itct)])};g.x(c5,b5);
c5.prototype.show=function(){if(!this.isActive){b5.prototype.show.call(this);if(!this.N){g.aq(this.xb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",La:["branding-img","iv-click-target"],Y:{"aria-label":"Marca de agua del canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.on(this.u,!1);var b=this.createElement({G:"button",La:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.xb().appendChild(b);var c=this.annotation.mf();c&&T4(this,
b,c,this.annotation.id,a.session_data);Rdb(this,a);this.N=!0}g.on(this.xb(),!0);this.isActive=!0;this.u&&(Odb(this,this.u),g.aq(this.context.I.getRootNode(),"ytp-branding-shown"))}};
c5.prototype.hide=function(){this.isActive&&(b5.prototype.hide.call(this),g.on(this.xb(),!1),this.isActive=!1,g.cq(this.context.I.getRootNode(),"ytp-branding-shown"))};
c5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);b5.prototype.destroy.call(this)};g.x(Tdb,b5);g.k=Tdb.prototype;g.k.show=function(){this.isActive||(b5.prototype.show.call(this),this.ea||(Vdb(this),this.ea=!0),g.on(this.xb(),!0),g.Mf(function(){g.cq(this.xb(),"iv-promo-inactive")},100,this),this.xb().removeAttribute("aria-hidden"),this.isActive=!0,Zdb(this),Wdb(this),Xdb(this,this.J))};
g.k.hide=function(){this.isActive&&(g.aq(this.xb(),"iv-promo-inactive"),this.isActive=!1,this.xb().setAttribute("aria-hidden","true"))};
g.k.oJ=function(a,b,c,d,e,f){return this.isCollapsed?!1:b5.prototype.oJ.call(this,a,b,c,d,e,f)};
g.k.O3=function(a){this.V=!0;Udb(this,500,a)};
g.k.N3=function(){this.V=!1;Ydb(this)};
g.k.I3=function(a){a.stopPropagation();this.hide()};
g.k.J3=function(a){a.stopPropagation();Zdb(this);this.isCollapsed=!0;g.aq(this.xb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();b5.prototype.destroy.call(this)};g.x(aeb,g.aU);g.k=aeb.prototype;g.k.Bh=function(a,b){if(!oeb(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.Y7a(b))&&feb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Cdb(this.j,b),x4(this.player)),!0}return null};
g.k.getOptions=function(){return oeb(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.ww=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.zd&&a.oa||g.NS(this.player.app)?!1:1===c&&!b.bS||a.Ja.get(b.videoId)||g.AO(b)||g.BO(b)?!0:!1};
g.k.nH=function(){if(this.B){var a=this.player.ob().getVideoContentRect(!0);g.mn(this.B.element,a.width,a.height);g.hn(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Gk();a=this.j;b=b.width;g.eq(a.C,"iv-drawer-small",426>=b);g.eq(a.C,"iv-drawer-big",1280<=b)}};
g.k.ZZ=function(a){ceb(this,a.state);g.BP(a.state,2)&&(this.xk()&&this.Eo()&&2!==this.player.getPresentingPlayerType()&&this.Pz(!1),this.Oz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Vy(h)&&h.responseXML?h.responseXML:null)&&(feb(b,h),g.aq(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.aU.prototype.load.call(this);ceb(this,this.player.Ib());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.FA()&&(a=geb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Ja.get(d);f&&heb(e,f);f=f&&(f.UK||f.fB);if(!c.rA||f)c.Oa?deb(this,c.Oa,e):(this.Fw=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();if((null==h?0:g.zO(h))&&!b.ea){var l,m;if(h=null==(l=h.pd)?void 0:null==(m=l.cards)?void 0:m.cardCollectionRenderer)b.ea=!0,meb(b,h),h.headerText&&b.lh&&(l=g.FF(h.headerText),b.lh.setAttribute("title",l))}},this.player.addEventListener("videodatachange",
this.Fw));
g.$S(this.player,this.B.element,4);this.nH();(f=g.AO(c))&&meb(this,f);(f=g.BO(c))&&f.featuredChannel&&neb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.lh=g.Re("ytp-cards-button",this.player.getRootNode())};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Oa&&deb(this,b.Oa,a)};
g.k.unload=function(){this.player.Me("annotations_module");for(var a=g.u(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.V=null;this.j&&(this.j.destroy(),this.j=null,x4(this.player));this.N=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.J={};this.u.hide();g.aU.prototype.unload.call(this);this.B.detach();this.Fw&&(this.player.removeEventListener("videodatachange",this.Fw),this.Fw=null)};
g.k.NW=function(a){a===this.player.getVideoData().videoId&&(this.loaded?ieb(this):this.load())};
g.k.xk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.Eo=function(){return!!this.j&&this.j.B};
g.k.Pz=function(a,b,c){b=void 0===b?!1:b;this.xk();this.j&&(a?c?V4(this.j,c,b):V4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):W4(this.j))};
g.k.Oz=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.W().Ja.unsubscribe("vast_info_card_add",this.NW,this);g.cq(this.player.getRootNode(),g.xX.IV_DRAWER_OPEN);for(var a=this.oa,b=g.Lp,c=0,d=a.length;c<d;c++)b.Nm(a[c]);this.oa.length=0;g.aU.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.I(this,a);return a.element};g.$T("annotations_module",aeb);g.$T("creatorendscreen",Vcb);})(_yt_player);
