(function(g){var window=this;'use strict';var teb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},ueb=function(a){return g.pM(a)?g.TK(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},veb=function(a,b){var c=new g.KM;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},web=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.LB(),2);if(3!=f.j){d=f.u;if(!d)throw g.ZA("gct");return g.z(f,g.CN(d),3)}e=f.u;return f.return(e.get("captions",c))})},xeb=function(a,b,c){web(a,b).then(function(d){d&&c(d.trackData,new g.KM(d.metadata))})},Aeb=function(a){if(!yeb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(zeb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Beb=function(){return g.lA("yt-player-caption-display-settings")},f5=function(){this.segments=[]},Ceb=function(a,b){var c=g.Ob(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Cb(a.segments,c),g.Cb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Kb(a.segments,c,0,b),g.Kb(a.segments,c+1,0,b)))},Deb=function(a,b,c,d,e,f){g.D.call(this);
this.policy=a;this.player=b;this.ea=c;this.onLoadCallback=d;this.D=e;this.V=f;this.C=new f5;this.J=-1;this.B=this.u=this.j=null;this.N=new g.Tp(this.wV,1E3,this);this.events=new g.MJ(this);g.I(this,this.N);g.I(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.sz);this.sz();this.wV()},Eeb=function(a){return a.j&&a.j.B?a.j.B+a.player.Kd()<a.player.getCurrentTime():!1},Feb=function(a,b){var c=g.cJ(b,a.policy,{}).mf(),d={format:"RAW",
withCredentials:!0};if(a.policy.Aa){d.method="POST";var e=b.Ks(),f=(0,g.sY)([120,0]);e&&g.mN(e,g.cLa);d.postBody=f}a.D&&(d.responseType="arraybuffer");a.B=g.ez(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.u){var l=!(a.D?h.response:h.responseText)||400<=h.status,m=g.gua(h);if(m){h=g.cJ(a.u,a.policy,{});a.u.Ik(h,m);Feb(a,a.u);break a}if(l)a.player.ya("capfail",{status:h.status});else if(a.player.Uh().Ai("fcb_r"),m=a.u.jb[0].Pa,null!=a.onLoadCallback&&a.J!==m){l=a.u.jb[0];if(a.D)a.onLoadCallback(h.response,
1E3*(l.startTime+a.player.Kd()));else a.onLoadCallback(h.responseText,1E3*(l.startTime+a.player.Kd()));a.J=m}}a.u=null;a.B=null}}).hk(function(h){a.u=null;
a.B=null;var l;a.player.ya("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.u=b;Ceb(a.C,a.u.jb[0].Pa)},g5=function(a,b){g.dU.call(this,b.W());
this.u=a;this.I=b;this.B=null;this.D=!1;this.J=g.rM(this.I.W())&&!this.u.isManifestless},Heb=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.dLa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.I.W().K("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.tcb.get(e);null==q&&(q=Geb[e]||Geb[e.replace(/-/g,"_")],g.tcb.set(e,q));h=q||h}c.push(new g.KM({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Ieb=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},Jeb=function(a,b,c){var d=[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.dLa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},Leb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in Keb?Keb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c.xA=d;var e=function(f){return function(){return String(a[f.xA])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.xA+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.xA,"gi"),e);c={xA:c.xA}}return b},h5=function(a,b,c,d,e,f,h,l,m,n){var p={};
Object.assign(p,b);Object.assign(p,a.params);Object.assign(p,c);var q={};Object.assign(q,b.Re);a.params.Re&&Object.assign(q,a.params.Re);Object.assign(q,c.Re);p.Re=q;var t=1===p.zi,v=[{G:"span",S:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],y,B,G;(l=l.rb("caption_edit_on_hover")&&(null==(y=n.getVideoData().getPlayerResponse())?void 0:null==(B=y.captions)?void 0:null==(G=B.playerCaptionsTracklistRenderer)?void 0:G.openTranscriptCommand))&&v.unshift({G:"button",S:"caption-edit",
Y:{tabindex:"0","aria-label":Leb()},X:[{G:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},X:[{G:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.W.call(this,{G:"div",S:"caption-window",Y:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:p.lang},X:v});var N=this;this.J=[];this.Ca=!1;this.u=a;this.Na=
this.Ja=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=.96*f;this.maxHeight=.96*h;this.j=p;this.Nc=c;this.Aa=b;this.C=this.Ea("captions-text");this.uc=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Oa=Meb(d,e,f,h);this.qd=m;l&&(this.D=this.Ea("caption-edit"),this.T(this.D,"click",function(){N.qd()}));
this.type=0;this.ib=this.Oa*Neb(q);a=new g.GT(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.c_,this);a.subscribe("dragmove",this.b_,this);a.subscribe("dragend",this.a_,this);this.qb=this.kb=this.Qb=this.ub=0;a="";this.j.windowOpacity&&(a=Aeb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":Oeb[this.j.textAlign]};this.uc&&(b["border-radius"]=a?this.ib/8+"px":"");(this.B=2===this.u.params.zi||
3===this.u.params.zi)&&Peb(this,this.element);g.bn(this.element,b);switch(this.j.Jl){case 0:case 1:case 2:g.aq(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.aq(this.element,"ytp-caption-window-bottom")}},Peb=function(a,b){var c="vertical-rl";
1===a.j.MP&&(c="vertical-lr");g.Te&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.bn(b,"-o-writing-mode",c);g.bn(b,"-webkit-writing-mode",c);g.bn(b,"writing-mode",c);g.bn(b,"text-orientation","upright");g.aq(b,"ytp-vertical-caption");3===a.u.params.zi&&(g.bn(b,"text-orientation",""),g.bn(b,"transform","rotate(180deg)"))},Neb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Qeb=function(a,b){var c={},d=b.background?b.background:a.j.Re.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Re.backgroundOpacity;d=Aeb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.uc&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ib/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Oa*Neb(b)+"px";d=1;e=b.color||a.j.Re.color;if(b.color||null!=b.textOpacity)e=Aeb(e),d=null==b.textOpacity?a.j.Re.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.VK&&(h=e=b.VK);var l=a.Oa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.sz()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Re.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.j4&&(c.visibility="hidden");1===b.PU&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.tM||g.XA,3===a.u.params.zi?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Nn||2===b.Nn||3===b.Nn||4===b.Nn||5===b.Nn)if(g.tM)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Nn){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Reb=function(a){a.N=g.Xe("SPAN");
g.bn(a.N,{display:"block"});g.aq(a.N,"caption-visual-line");a.C.appendChild(a.N)},Seb=function(a,b){var c=g.Xe("SPAN");
g.bn(c,{display:"inline-block","white-space":"pre-wrap"});g.bn(c,Qeb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.bn(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.bn(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Teb=function(a,b,c){a.Ca=a.Ca||!!c;
var d={};Object.assign(d,a.j.Re);Object.assign(d,c||b.j);Object.assign(d,a.Nc.Re);(c=!a.N)&&Reb(a);for(var e=a.Ja&&a.Na&&g.dd(d,a.Na)?a.Ja:Seb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(Reb(a),e=Seb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ye(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.tM||!g.dn(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.dn(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Kc?g.bn(e,m,"1em"):g.bn(e,m,"0.5em")))}a.Na=d;a.Ja=e;a.J.push(b)},Meb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},i5=function(a,b,c,d){g.dU.call(this,a);
this.videoData=b;this.audioTrack=c;this.Xa=d;this.C=b.SK},j5=function(a,b,c,d,e,f,h,l,m,n){h5.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},k5=function(a,b,c,d,e,f,h,l,m,n){h5.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.V=[];this.qa=this.oa=this.Va=0;this.Fa=NaN;this.Rb=0;this.vc=null;this.eb=new g.Tp(this.f7,433,this);this.D&&(n.vb(this.D,this,167342),this.T(this.D,"click",function(){n.tb(p.D)}),a=new g.GT(this.element,!0),g.I(this,a),a.subscribe("hoverstart",function(){n.Ya(p.D,!0)},this));
g.aq(this.element,"ytp-caption-window-rollup");g.I(this,this.eb);g.bn(this.element,"overflow","hidden")},Ueb=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.MP&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},Veb=function(a){a.V=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Tq,c=0,d=0,e=a.V.length-1;c<b&&-1<e;){var f=a.V[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.V.length<b&&(d*=b/a.V.length);a.oa=d;b=Math;c=b.max;isNaN(a.Fa)&&((d=a.j.Vr)?(e=g.Xe("SPAN"),g.jf(e,"\u2013".repeat(d)),g.bn(e,Qeb(a,a.j.Re)),a.C.appendChild(e),a.Fa=e.offsetWidth,a.C.removeChild(e)):a.Fa=0);d=a.C;a.qa=c.call(b,a.Fa,a.Rb,(a.B?d.offsetHeight:d.offsetWidth)+1)},Web=function(a,b){Veb(a);
var c=a.V.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.oa-c;if(c!==a.Va){var d=0<c&&0===a.Va;b||isNaN(c)||d||(g.aq(a.element,"ytp-rollup-mode"),g.Up(a.eb));g.bn(a.C,"transform",Ueb(a,c));a.Va=c}Veb(a)},l5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.xF.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},m5=function(a,b,c,d,e){g.xF.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Xeb=function(a){var b="_"+n5++;
return new m5(0,0x8000000000000,0,b,a)},Zeb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Xf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Yeb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new l5(a,b,e,c,l,d,m)}switch(m.Xf){case 9:case 10:m.Nn=1;break;case 11:m.Nn=2;break;case 12:m.Nn=3;break;case 13:m.Nn=4;break;case 14:m.Nn=5}return new l5(a,b,e,c,l.textContent||"",d,m)},Yeb=function(a,b,c,d,e){var f=g.sz(),h=
f?g.Xe("DIV"):g.Xe("RUBY"),l=g.Xe("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Xe("DIV"):g.Xe("RP");a.textContent=b;h.appendChild(a);b=f?g.Xe("DIV"):g.Xe("RT");b.textContent=c;h.appendChild(b);c=e.Xf;if(10===c||11===c||12===c||13===c||14===c)if(g.bn(b,"text-emphasis-style","filled circle"),g.bn(b,"text-emphasis-color","currentcolor"),g.bn(b,"webkit-text-emphasis","filled circle"),11===e.Xf||13===e.Xf)g.bn(b,"webkit-text-emphasis-position","under left"),g.bn(b,"text-emphasis-position","under left");c=!0;if(4===e.Xf||7===e.Xf||12===e.Xf||
14===e.Xf)g.bn(h,"ruby-position","over"),g.bn(h,"-webkit-ruby-position","before");else if(5===e.Xf||6===e.Xf||11===e.Xf||13===e.Xf)g.bn(h,"ruby-position","under"),g.bn(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Xe("DIV"):g.Xe("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.bn(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.bn(f,"display","none"),f=f.nextElementSibling,g.bn(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.bn(h.lastElementChild,"display","none"),d?(g.bn(h,"padding-top","0.6em"),g.bn(f,"top","0")):(g.bn(h,"padding-bottom","0.6em"),g.bn(f,"bottom","0")));return h},o5=function(){g.D.apply(this,arguments)},p5=function(a){o5.call(this);
this.C=a;this.pens={};this.V={};this.ea={};this.D="_"+n5++;this.N={};this.B=this.j=null;this.J=!0},q5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},r5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},s5=function(a,b){a=q5(a,b);
return void 0!==a?a:null},u5=function(a,b){a=a.getAttribute(b);
if(null!=a)return t5.test(a),a},$eb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.ea[d]:a.C);a=s5(b,"mh");null!=a&&(c.kz=a);a=s5(b,"ju");null!=a&&(c.textAlign=a);a=s5(b,"pd");null!=a&&(c.zi=a);a=s5(b,"sd");null!=a&&(c.MP=a);a=u5(b,"wfc");null!=a&&(c.windowColor=a);b=q5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},afb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.V[d]);a=s5(b,"ap");null!=a&&(c.Jl=a);a=q5(b,"cc");null!=a&&(c.Vr=a);a=q5(b,"ah");null!=a&&(c.Pj=a);a=q5(b,"rc");null!=a&&(c.Tq=a);b=q5(b,"av");null!=b&&(c.On=b);return c},bfb=function(a,b,c,d){var e={};
Object.assign(e,afb(a,b));Object.assign(e,$eb(a,b));d?g.dd(e,a.C)?(d=a.D,e=a.C):d="_"+n5++:d=b.getAttribute("id")||"_"+n5++;a=q5(b,"t")+c;b=q5(b,"d")||0x8000000000000;if(2===e.zi||3===e.zi)c=e.Tq,e.Tq=e.Vr,e.Vr=c;return new m5(a,b,0,d,e)},v5=function(a){o5.call(this);
this.J=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},w5=function(a){a=g.oe(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},cfb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Tq=a);b=b.ccColCount;void 0!==b&&(f.Vr=b);if(2===f.zi||3===f.zi)b=f.Tq,f.Tq=f.Vr,f.Vr=b;return new m5(c,d,0,e,f)},efb=function(){this.B=this.time=this.mode=this.u=0;
this.C=new dfb(this);this.D=new dfb(this);this.j=[];this.clear()},gfb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Hu:a,
Rr:b,result:0};a=ffb[a];b=ffb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Te()&&c.Rr===d;if(d)return{Hu:a,Rr:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Hu:a,Rr:b,result:2};return{Hu:a,Rr:b,result:3}},ifb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,hfb(a.C,b,c,d))},jfb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.u(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?ifb(a,d.aT,d.bT,b):1===d.type&&a.u&496&&hfb(a.D,d.aT,d.bT,b);a.j.length=0},x5=function(){this.type=0},y5=function(){this.state=this.Rr=this.Hu=0},kfb=function(){this.timestamp=this.j=0},z5=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new x5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new kfb}},A5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},pfb=function(a,b){switch(a){case 0:return lfb[(b&127)-32];
case 1:return mfb[b&15];case 2:return nfb[b&31];case 3:return ofb[b&31]}return 0},B5=function(a){return a.B[a.row][a.u]},C5=function(a,b,c){2<=b&&1<a.u&&(--a.u,B5(a).j=0);
var d=B5(a);d.timestamp=a.D.time+0;d.j=pfb(b,c);32>a.u&&a.u++},qfb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},D5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},rfb=function(a){a.row=0<a.j?a.j:1;
a.u=1;D5(a,0,15)},sfb=function(a){this.B=a;
this.D=0;this.style=new x5;this.J=new z5(this.B);this.N=new z5(this.B);this.text=new z5(this.B);this.u=this.J;this.C=this.N;this.j=this.u},tfb=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(A5(d,c),rfb(a.u),rfb(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(A5(d,c),D5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},ufb=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},vfb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},dfb=function(a){this.j=a;
this.D=0;this.B=new sfb(this.j);this.J=new sfb(this.j);this.u=new y5;this.C=this.B},hfb=function(a,b,c,d){a.u.update();
b=gfb(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Hu;c=b.Rr;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&C5(a,0,b),c&96&&C5(a,0,c),0!==b&&0!==c&&3===a.style.type&&A5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Hu=e,b.Rr=c,b.state=2,b=e&8?a.J:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;qfb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));D5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:C5(b.j,0,32);break a;case 48:57===c?(d=b.j,B5(d).j=0,32>d.u&&d.u++):C5(b.j,1,c&15)}break;case 2:c&32&&C5(b.j,2,c&31);break;case 3:c&32&&C5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:ufb(b);
break;case 33:d=b.j;1<d.u&&(--d.u,B5(d).j=0);break;case 36:d=b.j;b=B5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:tfb(b,2,d);break;case 38:tfb(b,3,d);break;case 39:tfb(b,4,d);break;case 40:C5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);rfb(d);vfb(b);break;case 43:vfb(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:A5(a,d)}D5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;A5(a,d);qfb(a,b,b+1,a.j-1);D5(a,a.row,1)}break;case 46:D5(b.C,0,15);break;case 47:A5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,ufb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},wfb=function(){},E5=function(a,b,c){this.trackData=a;
this.J=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},F5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},G5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},H5=function(a,b){o5.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new efb;this.j.u=1<<this.track},yfb=function(a){if("string"===typeof a)return!1;
a=new E5(a,8,0);return xfb(a)},xfb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==G5(a))return!1;
a.version=F5(a);if(1<a.version)return!1;F5(a);F5(a);F5(a);return!0},I5=function(){o5.call(this)},zfb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new l5(b,c,d,e.id,p.nodeValue,f||0<n,g.$c(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);zfb(a,b,c,d,e,!0,p,q,m)}}},Afb=function(a){var b=a.split(":");
a=0;b=g.u(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Bfb=function(a,b,c,d){d=Object.assign({kz:0},d);
return new m5(a,b,c,"_"+n5++,d)},J5=function(a,b){g.D.call(this);
this.I=a;this.Z=b;this.parser=null;this.j=this.I.Gy()},Hfb=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=Cfb(a,b,d),l=[];try{for(var m=g.u(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.EP;l="string"!==typeof q?l.concat(Dfb(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(Efb(a,q,t)):l.concat(Ffb(a,c,q,t))}var v=l}catch(y){g.cF(y),a.clear(),v=[]}if(0!==v.length)return v}b=Gfb(b);if(!b)return[];try{return"string"!==typeof b?Dfb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?Efb(a,b,d):Ffb(a,c,b,d)}catch(y){return g.cF(y),a.clear(),[]}},Gfb=function(a){if("string"===
typeof a||yfb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.HH(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.sH(a)},Cfb=function(a,b,c){if("string"===typeof b||yfb(b))return[{trackData:b,
EP:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Wsa(d);if(a.j&&e){var f=g.Osa(e),h=g.Psa(e);e=e.j;f&&e&&a.j.nE(e,f,h)}a=g.QH(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.sH(e),f.push({trackData:e,EP:c+1E3*h});Ifb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},Ifb=function(a,b,c){var d=g.HH(a,0,1836476516),e=9E4;
d&&(e=g.IH(d)||9E4);d=0;for(var f=g.QH(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.HH(a,l.dataOffset,1953653094))&&(l=g.HH(a,l.dataOffset,1952867444))&&(l=g.OH(l)/e*1E3,0===h&&(d=l),b[h].EP=l-d+c||c*h*1E3)}},Dfb=function(a,b,c,d,e){if(!yfb(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new H5(e,b));return a.parser.u(c,d)},Efb=function(a,b,c){a.parser||(a.parser=new I5);
a=a.parser.u(b,c);.01>Math.random()&&g.dF(Error("Deprecated subtitles format in web player: WebVTT"));return a},Ffb=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new v5(Jfb(b))),a.parser.u(c,d)}catch(f){return g.cF(f),[]}var e=g.Y7a(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new p5(Jfb(b),a.Z)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Jfb=function(a){var b=
{};
if(a=g.NM(a))b.lang=a,g.Z9a.test(a)&&(b.zi=1);return b},K5=function(a){g.aU.call(this,a);
var b=this;this.I=a;this.Z=this.I.W();this.videoData=this.I.getVideoData();this.ub=this.I.ob();this.B={Re:{}};this.D={Re:{}};this.Ca=[];this.qa={};this.Va={};this.oa=!1;this.uc=g.MO(this.videoData);this.kb=g.eLa(this.videoData,this.I);this.Rb=!!this.videoData.captionTracks.length;this.vc=!!this.videoData.Ed;this.eb="3"===this.Z.controlsType;this.j=this.N=this.V=this.Oa=this.qb=null;this.ib=new J5(this.I,this.Z);this.u=null;this.Fa=new g.MJ(this);this.J=new g.W({G:"div",S:"ytp-caption-window-container",
Y:{id:"ytp-caption-window-container"}});this.ea={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.Jq("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.xq(d));this.storage=c;var e;this.Ob=!(null==(e=a.Ke())||!e.gE());this.C=Kfb(this);this.Aa=!this.C&&this.eb&&this.Ob&&this.kb;g.I(this,this.ib);this.C?this.Na=this.Ja=null:(this.Ja=new g.Rp(this.eQ,void 0,this),g.I(this,this.Ja),this.Na=new g.Tp(this.C8,2E3,this),g.I(this,this.Na));g.I(this,this.Fa);g.$S(this.player,this.J.element,
4);g.I(this,this.J);this.C||this.Fa.T(a,"resize",this.gQ);(this.Qb=g.XL(this.Z)&&!g.Tz()&&!this.I.isFullscreen()&&!this.C&&!this.Aa)&&this.Fa.T(a,"resize",this.q6);this.Fa.T(a,"onPlaybackAudioChange",this.G5);this.Fa.T(a,g.zF("captions"),function(f){b.onCueRangeEnter(f)});
this.Fa.T(a,g.AF("captions"),function(f){b.onCueRangeExit(f)});
Lfb(this,Beb()||{});this.player.Qa("onCaptionsModuleAvailable")},Ofb=function(a){if(1===a.Z.Qb||1===a.videoData.yC||"alwayson"===g.qO(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.Z.Qb){if(g.pM(a.Z))var c=Mfb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=teb(a.player.getAudioTrack(),g.pM(a.Z));var d=g.qO(a.videoData,"yt:cc");if(void 0===Nfb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.qO(a.videoData,"yt:cc")},L5=function(a,b){if(a.u&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},Nfb=function(a){var b=void 0,c=g.sA(g.rA(),65);
if(g.pM(a.Z)&&null!=c){if(null!=Mfb(a))return!1;b=!c}return b},Pfb=function(a){var b;
a.uc?b=new i5(a.Z,a.videoData,a.player.getAudioTrack(),a.player):a.kb?b=new g5(a.videoData.j,a.player):a.Rb?b=new g.eU(a.Z,a.videoData,a.player.getAudioTrack()):b=new g.gU(a.Z,a.videoData.Ed,a.videoData.videoId,g.vya(a.videoData),a.videoData.zm,a.videoData.eventId);return b},N5=function(a,b){if(a.j){if(a.N&&a.N.C)return a.N.C;
g.DO(a.videoData)&&(b=!0);b||(b=a.vc?!1:a.Rb?!1:!0);b=b||Qfb(a);b=g.bU(a.j.j,b);var c=null;if(ueb(a.Z)){var d=a.I.isInline()?void 0:g.lA("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.qO(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.NM(b[m])===l)return b[m];l=l.split("-")[0];for(m=0;m<b.length;m++)if(g.NM(b[m])===l)return b[m]}}if(a.Z.K("web_player_always_enable_auto_translation")&&
f&&a.j&&(e=a.j.C,e.length))for(e=g.u(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.qO(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.NM(b[f])===d[e])return b[f];d=null;a.N&&a.N.B&&(d=a.N.B);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||M5(a));d&&c&&(d=veb(d,c));return d}return null},M5=function(a){return a.N&&a.N.j},O5=function(a){var b=M5(a);
return!!b&&a.u===b},Rfb=function(a){g.bU(a.j.j,!0);
var b=teb(a.player.getAudioTrack(),g.pM(a.Z)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=N5(a,a.oa):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&L5(a)?c=M5(a):Nfb(a)||a.oa||Ofb(a)?c=N5(a,a.oa):L5(a)&&(c=M5(a));if(a.C||a.Aa){var d=g.bU(a.j.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.Xe("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.LM(f));h.setAttribute("srclang",g.NM(f));h.setAttribute("id",f.toString());a.Aa||h.setAttribute("src",a.j.hv(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.I.Ke();c.XA(b);c=c.xb();a.Ob&&a.Fa.T(c.textTracks,"change",a.N7)}else!a.u&&c&&P5(a,c),a.player.Qa("onCaptionsTrackListChanged"),a.player.Qa("onApiChange")},Sfb=function(a,b){var c=a.I.Ke().xb().textTracks;
a=a.u.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},P5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.oa=c,a.oa&&(g.pM(a.Z)?Q5(a,!!b):R5(a,!!b)));a.u=b;L5(a)&&(a.u=M5(a));a.load()},Ufb=function(a,b){if(b instanceof m5){var c=a.qa[b.id];
c&&c.u!==b&&(c.dispose(),delete a.qa[b.id],c=null);c||(c=Tfb(a,b))&&(a.qa[b.id]=c)}else c=b.windowId,a.Va[c]||(a.Va[c]=[]),a.Va[c].push(b)},Tfb=function(a,b){var c=Vfb(a);
if(!c)return null;var d=a.u?g.NM(a.u):null;d&&g.Z9a.test(d)&&(b.params.zi=1);var e=a.ub.getPlayerSize();d=e.height*a.ea.height;e=e.width*a.ea.width;"google-live"!==a.Z.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.kz?b.params.kz:1<b.j.length?1:0){case 1:return new j5(b,a.B,a.D,c.width,c.height,e,d,a.Z.experiments,a.pJ.bind(a),a.I);case 2:return new k5(b,a.B,a.D,c.width,c.height,e,d,a.Z.experiments,a.pJ.bind(a),a.I);default:return new h5(b,a.B,a.D,c.width,c.height,e,
d,a.Z.experiments,a.pJ.bind(a),a.I)}},Lfb=function(a,b,c){c=void 0===c?!1:c;
var d=S5.Re;a.B={};Object.assign(a.B,S5);a.B.Re={};Object.assign(a.B.Re,d);a.D={Re:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;t5.test(f);e.Re.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;t5.test(f);e.Re.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||S5.windowColor;t5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Re.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Re.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Re;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Re.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=S5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Re.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Re.fontFamily=f;a.loaded&&a.gQ();c&&g.kA("yt-player-caption-display-settings",b,2592E3)},Xfb=function(a,b,c){b&&!a.V?(b=Xeb({zi:0,
lang:"es"}),a.V=[b,new l5(b.start,b.end-b.start,0,b.id,null!=c?c:"Los subt\u00edtulos tendr\u00e1n este aspecto")],a.player.bf(a.V)):!b&&a.V&&(Wfb(a,a.V),a.V=null)},Wfb=function(a,b){a.player.qp(b);
b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.Db(a.Ca,c.value);g.Sp(a.Ja)},Vfb=function(a){var b=a.ub.getVideoContentRect(!0).height,c=a.ub.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ea.height;c*=a.ea.width;return{width:c,height:b}},R5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},Q5=function(a,b){a.I.isInline()||g.kA("yt-player-sticky-caption",b,2592E3)},Mfb=function(a){if(!a.I.isInline())return g.lA("yt-player-sticky-caption")},Kfb=function(a){var b,c=!(null==(b=a.I.Ke())||!b.fE());
return a.eb&&c&&!a.kb},Qfb=function(a){return a.Z.K("web_deprecate_always_includes_asr_setting")&&g.pM(a.Z)?!0:!!g.sA(g.rA(),66)};
g.aX.prototype.KB=g.da(40,function(a){var b=2;this.Aa.has(a)?b=0:g.XQa(this,a)&&(b=1);return b});
g.bZ.prototype.KB=g.da(39,function(a){return this.wd.KB(a)});
g.aX.prototype.nE=g.da(38,function(a,b,c){this.Oa.set(a,{gs:b,Lx:c})});
g.bZ.prototype.nE=g.da(37,function(a,b,c){this.wd.nE(a,b,c)});
g.dU.prototype.GO=g.da(30,function(){return!1});
g.dU.prototype.Ys=g.da(29,function(){});
g.eU.prototype.Ys=g.da(28,function(a,b,c){var d=this;this.isDisposed();b=this.hv(a,b);this.Ar();this.u=g.az(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.gU.prototype.Ys=g.da(27,function(a,b,c){var d=this;this.isDisposed();b=this.hv(a,b);this.Ar();this.u=g.az(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.MT.prototype.Yx=g.da(26,function(){for(var a=g.Ne(document,"track",void 0,this.j),b=0;b<a.length;b++)g.ff(a[b])});
g.OW.prototype.Yx=g.da(25,function(){this.mediaElement.Yx()});
g.MT.prototype.gE=g.da(24,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.OW.prototype.gE=g.da(23,function(){return this.mediaElement.gE()});
g.MT.prototype.fE=g.da(22,function(){return!!this.j.textTracks});
g.OW.prototype.fE=g.da(21,function(){return this.mediaElement.fE()});
g.MT.prototype.XA=g.da(20,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.OW.prototype.XA=g.da(19,function(a){this.mediaElement.XA(a)});
g.WY.prototype.aC=g.da(9,function(){return this.J});
g.i_.prototype.aC=g.da(8,function(){var a;return(null==(a=g.JS(this))?void 0:a.Gy())||null});
g.TS.prototype.Gy=g.da(7,function(){return this.app.aC()});
g.VZ.prototype.Gy=g.da(6,function(){var a;return(null==(a=this.Ga)?void 0:a.aC())||null});
g.gH.prototype.iG=g.da(2,function(a){return(a=this.Mo(a))?a.j:0});
g.tJ.prototype.iG=g.da(1,function(){return 0});
var zeb=/#(.)(.)(.)/,yeb=/^#(?:[0-9a-f]{3}){1,2}$/i,Geb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};f5.prototype.contains=function(a){a=g.Ob(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
f5.prototype.length=function(){return this.segments.length/2};
g.x(Deb,g.D);g.k=Deb.prototype;g.k.va=function(){g.D.prototype.va.call(this);this.B&&this.B.cancel()};
g.k.sz=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Kd();var b=this.j;this.j=g.ub(this.ea.cq(a).jb);b!==this.j&&this.V&&this.V()};
g.k.reset=function(){this.C=new f5;this.J=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.wV=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Kr(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.NA(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.Gy()){var c=a.jb[0].j.info.id,d=a.jb[0].Pa,e=a.jb[0].C;if(this.policy.Aa){if(b=b.Ks(e,d,c,3))a.J=b}else if(c=b.No(e,d,c,3))if(b=b.KB(d),0===b)c&&(a.u=new g.$G(c));else if(2===b){this.N.start();Eeb(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.jb[0].duration?(this.C.contains(a.jb[0].Pa)||Feb(this,a),this.j=g.ub(a.jb)):Eeb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.x(g5,g.dU);g.k=g5.prototype;g.k.Ys=function(a,b,c){var d=this;this.Ar();b=Ieb(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?Jeb(this,b,"386"):Jeb(this,b));if(b){var e=1E3*(b.index.iG(b.index.Tm())-b.index.getStartTime(b.index.Tm())),f=new g.JKa(this.Z);this.B=new Deb(f,this.I,b,function(h,l){c(h,a,l,e)},this.J||g.pJ(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.GO=function(){var a=this.D;this.D=!1;return a};
g.k.Zy=function(a){var b=this.J?[new g.KM({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.KM({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?Heb(this,"386"):Heb(this);b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.cU(this.j,c.value);a()};
g.k.Ar=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.hv=function(){return""};
var t5=/^#(?:[0-9a-f]{3}){1,2}$/i,Keb=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Ma("yt.msgs_",Keb);var Oeb=["left","right","center","justify"];g.x(h5,g.W);g.k=h5.prototype;g.k.c_=function(a,b){this.kb=a;this.qb=b;var c=g.ln(this.element,this.element.parentElement);this.ub=a-c.x;this.Qb=b-c.y};
g.k.b_=function(a,b){if(a!==this.kb||b!==this.qb){g.$p(this.element,"ytp-dragging")||g.aq(this.element,"ytp-dragging");var c=g.nn(this.element);a=a-this.ub-.02*this.playerWidth;var d=b-this.Qb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.oe(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.oe(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.oe(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.oe(c,0,1);this.u.params.Jl=b;this.u.params.On=c;this.u.params.Pj=
a;this.u.params.isDefault=!1;this.j.Jl=b;this.j.On=c;this.j.Pj=a;this.j.isDefault=!1;this.Aa.Jl=b;this.Aa.On=c;this.Aa.Pj=a;this.Aa.isDefault=!1;this.vX()}};
g.k.a_=function(){g.cq(this.element,"ytp-dragging")};
g.k.vX=function(){this.Vz(this.J)};
g.k.getType=function(){return this.type};
g.k.Vz=function(a){var b=Math.min(this.aU(),this.maxWidth),c=this.ZT(),d="";3===this.u.params.zi&&(d="rotate(180deg)");g.bn(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.CK(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Pj+2,f=this.j.Jl;switch(f){case 0:case 3:case 6:(b=this.j.Re.fontSizeIncrement)&&0<b&&2!==this.j.zi&&3!==
this.j.zi&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.On+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-b+"%"}g.bn(this.element,
d);if(this.D){c=this.C.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);c/=d;this.D.style.height=c+"px";this.D.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.CK=function(a){var b;for(b=0;b<a.length&&a[b]===this.J[b];b++);if(this.Ca||this.J.length>b)b=0,this.Ca=!1,this.J=[],this.N=this.Na=this.Ja=null,g.$e(this.C);for(;b<a.length;b++)Teb(this,a[b])};
g.k.aU=function(){return 0};
g.k.ZT=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.x(i5,g.dU);i5.prototype.Ys=function(a,b,c){xeb(this.videoData.videoId,a.vssId,c)};
i5.prototype.Zy=function(a){if(this.audioTrack)for(var b=g.u(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.cU(this.j,c.value);a()};g.x(j5,h5);j5.prototype.CK=function(a){var b=this.u.j;h5.prototype.CK.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Yfb);var e=c.j;var f=d}Teb(this,c,d)}};
var Yfb={j4:!0};g.x(k5,h5);g.k=k5.prototype;g.k.vX=function(){g.Vp(this.eb)};
g.k.f7=function(){g.cq(this.element,"ytp-rollup-mode");this.Vz(this.vc,!0)};
g.k.ZT=function(){return this.B?this.qa:this.oa};
g.k.aU=function(){return this.B?this.oa:this.qa};
g.k.Vz=function(a,b){this.vc=a;if(this.u.params.Tq){for(var c=0,d=0;d<this.J.length&&c<a.length;d++)this.J[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.J.concat(a.slice(c)));this.Rb=this.qa;this.oa=this.qa=0;h5.prototype.Vz.call(this,a);Web(this,b)}h5.prototype.Vz.call(this,a)};g.x(l5,g.xF);l5.prototype.toString=function(){return g.xF.prototype.toString.call(this)};g.x(m5,g.xF);m5.prototype.toString=function(){return g.xF.prototype.toString.call(this)};
var n5=0;g.x(o5,g.D);o5.prototype.u=function(){return[]};
o5.prototype.reset=function(){};g.x(p5,o5);p5.prototype.reset=function(){this.N={};this.B=this.j=null;this.J=!0};
p5.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.u(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.u(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=r5(a,"b");
null!=l&&(h.bold=l);l=r5(a,"i");null!=l&&(h.italic=l);l=r5(a,"u");null!=l&&(h.underline=l);l=s5(a,"et");null!=l&&(h.charEdgeStyle=l);l=s5(a,"of");null!=l&&(h.offset=l);l=u5(a,"bc");null!=l&&(h.background=l);l=u5(a,"ec");null!=l&&(h.VK=l);l=u5(a,"fc");null!=l&&(h.color=l);l=s5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=q5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=q5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=q5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=s5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Xf=10<l?l-1:l);a=s5(a,"hg");null!=a&&(h.PU=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.ea[c]=$eb(this,a);break;case "wp":c=a.getAttribute("id"),this.V[c]=afb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.u(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=bfb(this,a,b,!1);(a=this.N[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.N[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!r5(a,"a");l=(q5(a,"t")||0)+l;var m=q5(a,"d")||5E3;h||(!this.J&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.J=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var v=q[t],y=void 0;0<t&&(h=!0);var B=void 0;1===v.nodeType&&(B=v);if(B&&"s"===B.tagName){if((v=(v=B.getAttribute("p"))?this.pens[v]:null)&&v.Xf&&(1===v.Xf?(v=q.slice(t,t+
4),4===v.length&&(y=Zeb(l,m,f,h,n,v,this.pens),t+=3)):y=Zeb(l,m,f,h,n,[B],this.pens)),!y){var G=B;y=l;B=m;v=f;var N=h,L=n,H=G.textContent?G.textContent:"",V=G.getAttribute("p");V=V?this.pens[V]:null;G=q5(G,"t")||0;y=new l5(y+G,B-G,L,v,H,N,V)}}else y=new l5(l,m,n,f,v.textContent||"",h,p);c.push(y);this.B=y}if(0<c.length)for(c[0].windowId===this.D&&(this.j=bfb(this,a,b,!0),d.push(this.j)),a=g.u(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Zfb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.x(v5,o5);v5.prototype.reset=function(){this.B.clear()};
v5.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.u(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.VK=w5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=w5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=w5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Xf=10<h?h-1:h,f.Nn=Zfb.get(f.Xf));e.hgHorizGroup&&(f.PU=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.u(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.J),void 0!==e.mhModeHint&&(f.kz=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.zi=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.MP=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=w5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.u(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Pj=e.ahHorPos),void 0!==e.apPoint&&(f.Jl=e.apPoint),void 0!==e.avVerPos&&(f.On=e.avVerPos),void 0!==e.ccCols&&(f.Vr=e.ccCols),void 0!==e.rcRows&&(f.Tq=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.u(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=cfb(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+n5++,h=cfb(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],v=t.utf8;if(v){var y=t.tOffsetMs||0,B=null;t.pPenId&&(B=this.j.get(t.pPenId));if(2===(null!=h.params.kz?h.params.kz:1<h.j.length?1:0)&&m&&"\n"===v)continue;if(t=B&&1===B.Xf)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var G=p[t+1].pPenId;(G=this.j.get(G))&&G.Xf&&2===G.Xf?(G=p[t+2].pPenId,G=this.j.get(G),!G||!G.Xf||3>G.Xf?t=!1:(G=p[t+3].pPenId,t=(G=this.j.get(G))&&
G.Xf&&2===G.Xf?!0:!1)):t=!1}if(t){y=p[l+1].utf8;t=p[l+3].utf8;G=p[l+2].utf8;var N=this.j.get(p[l+2].pPenId);v=Yeb(v,y,G,t,N);m=new l5(d,e,n,f,v,m,B);l+=3}else m=new l5(d+y,e-y,n,h.id,v,m,B||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};efb.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
efb.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var ffb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];x5.prototype.set=function(a){this.type=a};
x5.prototype.get=function(){return this.type};
y5.prototype.clear=function(){this.state=0};
y5.prototype.update=function(){this.state=2===this.state?1:0};
y5.prototype.Te=function(){return 0!==this.state};
y5.prototype.matches=function(a,b){return this.Te()&&a===this.Hu&&b===this.Rr};
kfb.prototype.reset=function(){this.timestamp=this.j=0};
z5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
z5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
z5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var lfb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],mfb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],nfb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],ofb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];sfb.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.J;this.C=this.N;this.j=this.u;var c=(a<<2)+(b<<1);this.J.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
dfb.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.J.reset(a,1)};wfb.prototype.C=function(){};g.x(E5,wfb);E5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+n5++;c=c/1E3-this.J;d=d/1E3-this.J;a=new m5(c,d-c,5,f,{textAlign:0,Jl:0,Pj:2.5*b,On:5.33*a});e=new l5(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.x(H5,o5);H5.prototype.u=function(a){a=new E5(a,a.byteLength,this.B);if(xfb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=G5(a)*(1E3/45):1===a.version&&(a.B=4294967296*G5(a)+G5(a)),a.D=F5(a);0<a.D;a.D--){var b=F5(a),c=F5(a),d=F5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,aT:c,bT:d,order:b.j.length}))}jfb(this.j,a);return a.u}return[]};
H5.prototype.reset=function(){this.j.clear()};g.x(I5,o5);
I5.prototype.u=function(a,b){var c=[];a=a.split($fb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!agb.test(e)){var h=bgb.exec(e);if(h&&4<=h.length){var l=Afb(h[1]),m=Afb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,v="";n=g.u(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var B=y[1];switch(y[0]){case "line":y=B.split(",");y[0].endsWith("%")&&(p=y[0],h.On=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
B.split(",");t=y[0];h.Pj=Number.parseInt(t,10);2===y.length&&(v=y[1].trim());break;case "align":switch(B){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.Pj=0;break;case 1:h.Pj=100;break;case 2:h.Pj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(v){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Jl=q}e=e.substring(bgb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=Bfb(l,m,5,v),m=new l5(l,m,5,f.id,h,!1,g.$c(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(cgb),1===q.length?(h=5,v=Bfb(l,m,h,v)):(p=h=6,v=Object.assign({Vr:32},v),v=new m5(l,m,p,"_"+n5++,v)),c.push(v),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(y=g.Y7a("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(B=y.createElement("span"),B.appendChild(y.createTextNode(n))):B=y.firstChild,zfb(this,p,m-(p-l),h,v,0<t,B,e,c)):p=Afb(n)+f}bgb.lastIndex=0}}return c};
var agb=/^NOTE/,$fb=/(?:\r\n|\r|\n){2,}/,bgb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),cgb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.PW.xv(I5,{u:"wvppt"});g.x(J5,g.D);J5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
J5.prototype.reset=function(){this.parser&&this.parser.reset()};
J5.prototype.va=function(){g.D.prototype.va.call(this);this.clear()};var S5={windowColor:"#080808",windowOpacity:0,textAlign:2,Jl:7,Pj:50,On:100,isDefault:!0,Re:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.x(K5,g.aU);g.k=K5.prototype;g.k.va=function(){if(this.C||this.Aa){var a=this.I.Ke();a&&!a.isDisposed()&&a.Yx()}else Xfb(this,!1);g.aU.prototype.va.call(this)};
g.k.ww=function(){if(this.eb)return this.C||this.Aa;var a=this.player.getAudioTrack();if(this.Z.K("html5_honor_caption_availabilities_in_audio_track")){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=teb(a,g.pM(this.Z));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?L5(this):Nfb(this)||L5(this)?!0:Ofb(this)};
g.k.load=function(){var a=this;g.aU.prototype.load.call(this);this.N=this.player.getAudioTrack();this.j?this.u&&(this.ib.clear(),this.C?Sfb(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.Ys(this.u,"json3",function(b,c,d,e){b&&(a.Z.K("html5_modify_caption_vss_logging")&&(a.videoData.Pw=a.u||void 0),a.j.GO()&&(a.Ca=[],a.I.Me("captions"),g.Sp(a.Ja),a.ib.reset()),b=Hfb(a.ib,b,c,d,e),a.player.bf(b,void 0,a.kb),!a.oa||a.Aa||O5(a)||g.fM(a.Z)||g.ZL(a.Z)||g.$L(a.Z)||"shortspage"===a.Z.Na||a.player.isInline()||
(g.Wp(a.Na),b=Xeb({Jl:0,Pj:5,On:5,Tq:2,textAlign:0,zi:0,lang:"es"}),a.Oa=[b],c=["Haz clic en "," para ir a la configuraci\u00f3n"],a.qb||(d=new g.aR(g.fDa()),g.I(a,d),a.qb=d.element),d=b.end-b.start,(e=g.LM(a.u))&&a.Oa.push(new l5(b.start,d,0,b.id,e)),a.Oa.push(new l5(b.start,d,0,b.id,c[0]),new l5(b.start,d,0,b.id,a.qb,!0),new l5(b.start,d,0,b.id,c[1],!0)),a.player.bf(a.Oa),g.Up(a.Na)),!a.oa||a.Aa||O5(a)||(g.pM(a.Z)?Q5(a,!0):R5(a,!0),a.N&&(a.N.C=a.u),a.player.Bp()),a.oa=!1)}),this.C||this.Aa||O5(this)||
this.player.Qa("captionschanged",g.MM(this.u))):(this.j=Pfb(this),g.I(this,this.j),this.j.Zy(function(){Rfb(a)}))};
g.k.unload=function(){this.C&&this.u?Sfb(this,!1):(this.Na&&g.Wp(this.Na),this.player.Me("captions"),this.Ca=[],this.j&&this.j.Ar(),this.ib.clear(),this.V&&this.player.bf(this.V),this.gQ());g.aU.prototype.unload.call(this);this.player.Bp();this.player.Qa("captionschanged",{})};
g.k.create=function(){this.ww()&&this.load();var a;a:{var b,c,d;if(this.Z.K("suggest_caption_correction_menu_item")&&this.Z.K("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.u(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.I.ma("showpromotooltip",this.J.element)};
g.k.N7=function(){for(var a=this.I.Ke().xb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.bU(this.j.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.u:null)!==b&&P5(this,b,!0)};
g.k.J9=function(){!this.u&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ca.push(a);g.Sp(this.Ja)};
g.k.onCueRangeExit=function(a){g.Db(this.Ca,a);this.j instanceof g5&&this.j.J&&this.player.qp([a]);g.Sp(this.Ja)};
g.k.getCaptionWindowContainerId=function(){return this.J.element.id};
g.k.C8=function(){Wfb(this,this.Oa);this.Oa=null};
g.k.eQ=function(){var a=this;if(!this.Qb||!this.C){this.Ja.stop();g.gba(this.Va);this.Ca.sort(g.yF);var b=this.Ca;if(this.V){var c=g.eo(b,function(f){return-1===this.V.indexOf(f)},this);
c.length&&(b=c)}b=g.u(b);for(c=b.next();!c.done;c=b.next())Ufb(this,c.value);b={};c=g.u(Object.entries(this.qa));for(var d=c.next();!d.done;b={mu:b.mu,xm:b.xm},d=c.next()){var e=g.u(d.value);d=e.next().value;e=e.next().value;b.mu=d;b.xm=e;this.Va[b.mu]?(b.xm.element.parentNode||(b.xm instanceof k5||b.xm instanceof j5||g.Tc(this.qa,function(f){return function(h,l){l!==f.mu&&h.u.params.Jl===f.xm.u.params.Jl&&h.u.params.Pj===f.xm.u.params.Pj&&h.u.params.On===f.xm.u.params.On&&(h.dispose(),delete a.qa[l]);
return l===f.mu}}(b),this),this.J.element.appendChild(b.xm.element)),b.xm.Vz(this.Va[b.mu])):(b.xm.dispose(),delete this.qa[b.mu])}}};
g.k.H8=function(){Lfb(this,{},!0);this.player.Qa("captionssettingschanged")};
g.k.C3=function(){var a=S5.Re;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:S5.windowColor,windowOpacity:S5.windowOpacity};var b=Beb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.RY=function(a,b){var c={};Object.assign(c,Beb());Object.assign(c,a);Lfb(this,c,b);this.player.Qa("captionssettingschanged")};
g.k.gQ=function(){!this.C&&this.loaded&&(g.Pc(this.qa,function(a,b){a.dispose();delete this.qa[b]},this),this.eQ())};
g.k.Bh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.oe(b,-2,4);this.RY({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&P5(this,this.u,!0);break;case "stickyLoading":void 0!==b&&this.Z.J&&(g.pM(this.Z)?Q5(this,!!b):R5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.C)break;if(!g.Ra(b))break;if(g.$c(b)){P5(this,null,!0);break}a=g.bU(this.j.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
this.Z.K("html5_enable_caption_changes_for_mosaic")&&(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?veb(e,b.translationLanguage):e)}this.FI(b.position);!c||c===this.u&&this.loaded||(a=g.HK(),b=g.NM(c),a.length&&b===a[a.length-1]||(a.push(b),g.kA("yt-player-caption-language-preferences",a)),(a=ueb(this.Z))&&!this.I.isInline()&&g.kA("yt-player-caption-sticky-language",b,86400*a),P5(this,c,!0))}else return this.loaded&&this.u&&!O5(this)?g.MM(this.u):{};return"";case "tracklist":return this.j?
g.sm(g.bU(this.j.j,!(!b||!b.includeAsr)),function(f){return g.MM(f)}):[];
case "translationLanguages":return this.j?this.j.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||Xfb(this,!!b);break;case "sampleSubtitlesCustomized":this.C||Xfb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.HK()}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Z.J&&a.push("stickyLoading");return a};
g.k.fq=function(){var a=this.u;this.Z.K("html5_modify_caption_vss_logging")&&(a=this.videoData.Pw||null);if(a){var b=a.vssId;a.translationLanguage&&b&&(b="t"+b+"."+g.NM(a));return{cc:b}}return{}};
g.k.x9=function(){this.isSubtitlesOn()?(g.pM(this.Z)?Q5(this,!1):R5(this,!1),this.Z.K("html5_modify_caption_vss_logging")&&(this.videoData.Pw=void 0),this.unload(),L5(this,!0)&&P5(this,M5(this),!1)):this.xY()};
g.k.xY=function(){this.isSubtitlesOn()||P5(this,O5(this)||!this.u?N5(this,!0):this.u,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.u&&!O5(this)};
g.k.G5=function(){var a=O5(this);L5(this,a)?P5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Z.K("html5_honor_caption_availabilities_in_audio_track")&&(this.oa=!1,this.u=null,this.j&&(this.j.dispose(),this.j=null)),this.ww()&&(a?P5(this,N5(this),!1):this.load()))};
g.k.FI=function(a){a&&(this.ea={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.J.element.style.top=100*this.ea.top+"%",this.J.element.style.left=100*this.ea.left+"%",this.J.element.style.width=100*this.ea.width+"%",this.J.element.style.height=100*this.ea.height+"%",this.Z.K("html5_enable_caption_changes_for_mosaic")&&(this.J.element.style.position="absolute",a=Vfb(this)))&&(this.J.element.style.width=a.width+"px",this.J.element.style.height=
a.height+"px")};
g.k.q6=function(){var a=this.I.Ke();a&&!a.isDisposed()&&a.Yx();this.I.isFullscreen()?(this.C=this.eb=!0,this.loaded&&Rfb(this)):(this.eb="3"===this.Z.controlsType,this.C=Kfb(this));P5(this,this.u)};
g.k.pJ=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Qa("innertubeCommand",d)};
g.PW.xv(K5,{eQ:"smucd"});g.$T("captions",K5);})(_yt_player);
